# Generated by Django 3.2.6 on 2021-09-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210906_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='user',
        ),
    ]
