# Generated by Django 3.2.6 on 2021-09-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
