# Generated by Django 3.2.6 on 2021-09-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
