# Generated by Django 3.1.5 on 2021-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_profile', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
