# Generated by Django 3.2.6 on 2021-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_profile', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='media/Profile.png', null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
