# Generated by Django 3.2.6 on 2021-09-20 12:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_profile', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='user'),
            preserve_default=False,
        ),
    ]
