# Generated by Django 3.2.6 on 2021-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='media/1.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
